### ISSUE TITLE
Cannot read properties of undefined (reading 'status') - ArgoCD Plugin Error

### ISSUE THREAD

**Issue by dfl-aeb** [RoadieHQ/roadie-backstage-plugins#1034]
"ArgoCD" page throws an error after installation

## Expected Behavior

The argo cd page (or a page where the argo plugin is included) opens as intended

## Current Behavior

```
TypeError
Cannot read properties of undefined (reading 'status')
Call Stack
 eval
  plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDHistoryCard.tsx:57:24
 HistoryTable
  plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDHistoryCard.tsx:56:45
 renderWithHooks
  node_modules/react-dom/cjs/react-dom.development.js:14985:18
 mountIndeterminateComponent
  node_modules/react-dom/cjs/react-dom.development.js:17811:13
 beginWork
  node_modules/react-dom/cjs/react-dom.development.js:19049:16
 HTMLUnknownElement.callCallback
  node_modules/react-dom/cjs/react-dom.development.js:3945:14
 Object.invokeGuardedCallbackDev
  node_modules/react-dom/cjs/react-dom.development.js:3994:16
 invokeGuardedCallback
  node_modules/react-dom/cjs/react-dom.development.js:4056:31
 beginWork$1
  node_modules/react-dom/cjs/react-dom.development.js:23959:7
```
<

## Steps to Reproduce

1. Follow the Plugin installation instructions
2. Configure ArgoCD Api in `app-config.yaml`
4. Navigate to a component's "ArgoCD" page

## Possible Solution

I assume it has something to do with the latest ArgoCD Api version? It stopped working  a few weeks ago.

## Your Environment
- ArgoCD Server v2.7.5+a2430af.dirty
- `@backstage/plugin-catalog-react` version: 1.7.0
- `@backstage/integration` version: 1.5.0
- Tested with Backstage 1.13, 1.14.1 and 1.15.0

## Stacktrace in Developer Console:
<details><summary>Stacktrace in Developer Console:</summary>

The above error occurred in the <HistoryTable> component:

    at HistoryTable (webpack-internal:///../../plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDHistoryCard.tsx:50:25)
    at ArgoCDHistory (webpack-internal:///../../plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDHistoryCard.tsx:214:26)
    at ErrorBoundary2 (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:2447:5)
    at ArgoCDHistoryCard (webpack-internal:///../../plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDHistoryCard.tsx:301:99)
    at D (webpack-internal:///../../node_modules/react-router/index.js:35:685)
    at E (webpack-internal:///../../node_modules/react-router/index.js:38:820)
    at Router (webpack-internal:///../../plugins/frontend/backstage-plugin-argo-cd/src/Router.tsx:42:99)
    at RoutableExtensionWrapper (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:572:31)
    at PluginProvider (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/esm/usePluginOptions-68e31f9f.esm.js:13:11)
    at AnalyticsContext (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:72:11)
    at PluginErrorBoundary (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:538:5)
    at Suspense
    at Result (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:635:21)
    at article
    at Content (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:5166:11)
    at RoutedTabs (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:5285:11)
    at main
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:41:24)
    at Page (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:6258:11)
    at EntityLayout (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-a2e41e34.esm.js:1161:5)
    at EntitySwitch (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-a2e41e34.esm.js:1341:110)
    at EntitySwitch (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-a2e41e34.esm.js:1341:110)
    at B (webpack-internal:///../../node_modules/react-router/index.js:35:616)
    at AnalyticsContext (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:72:11)
    at AsyncEntityProvider (webpack-internal:///../../node_modules/@backstage/plugin-catalog-react/dist/esm/useEntity-de64059a.esm.js:33:11)
    at CatalogEntityPage (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-f0e32dd1.esm.js:40:162)
    at RoutableExtensionWrapper (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:572:31)
    at PluginProvider (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/esm/usePluginOptions-68e31f9f.esm.js:13:11)
    at AnalyticsContext (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:72:11)
    at PluginErrorBoundary (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:538:5)
    at Suspense
    at Result (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:635:21)
    at D (webpack-internal:///../../node_modules/react-router/index.js:35:685)
    at FlatRoutes (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:3364:81)
    at div
    at StyledComponent (webpack-internal:///../../node_modules/@material-ui/styles/esm/styled/styled.js:95:28)
    at SidebarPinStateProvider (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:3769:11)
    at SidebarPage (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4031:82)
    at Root (webpack-internal:///./src/components/Root/Root.tsx:107:17)
    at D (webpack-internal:///../../node_modules/react-router/index.js:35:685)
    at E (webpack-internal:///../../node_modules/react-router/index.js:38:820)
    at x (webpack-internal:///../../node_modules/react-router/index.js:37:23)
    at w (webpack-internal:///../../node_modules/react-router-dom/index.js:42:23)
    at AppRouter (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2164:138)
    at RoutingProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2713:3)
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:41:24)
    at StylesProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/StylesProvider/StylesProvider.js:49:24)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:42:5)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:51:5)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/material/styles/ThemeProvider.js:23:14)
    at StyledEngineProvider (webpack-internal:///../../node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:28:5)
    at UnifiedThemeProvider (webpack-internal:///../../node_modules/@backstage/theme/dist/index.esm.js:659:11)
    at Provider (webpack-internal:///../../node_modules/@backstage/app-defaults/dist/index.esm.js:337:18)
    at AppThemeProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2904:29)
    at AppContextProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2784:3)
    at ApiProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:80:11)
    at Provider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:3167:25)
    at App

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary2.
overrideMethod @ react_devtools_backend_compact.js:2367
logCapturedError @ react-dom.development.js:20085
callback @ react-dom.development.js:20154
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20709
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
scheduleUpdateOnFiber @ react-dom.development.js:21893
dispatchAction @ react-dom.development.js:16139
eval @ useAsyncFn.js:20
Promise.then (async)
eval @ useAsyncFn.js:19
eval @ useAsync.js:9
invokePassiveEffectCreate @ react-dom.development.js:23487
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23574
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23447
eval @ react-dom.development.js:23324
workLoop @ scheduler.development.js:417
flushWork @ scheduler.development.js:390
performWorkUntilDeadline @ scheduler.development.js:157
react_devtools_backend_compact.js:2367 ErrorBoundary, error: TypeError: Cannot read properties of undefined (reading 'status'), info: [object Object] 
    at ErrorBoundary2 (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:2447:5)
    at ArgoCDHistoryCard (webpack-internal:///../../plugins/frontend/backstage-plugin-argo-cd/src/components/ArgoCDHistoryCard.tsx:301:99)
    at D (webpack-internal:///../../node_modules/react-router/index.js:35:685)
    at E (webpack-internal:///../../node_modules/react-router/index.js:38:820)
    at Router (webpack-internal:///../../plugins/frontend/backstage-plugin-argo-cd/src/Router.tsx:42:99)
    at RoutableExtensionWrapper (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:572:31)
    at PluginProvider (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/esm/usePluginOptions-68e31f9f.esm.js:13:11)
    at AnalyticsContext (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:72:11)
    at PluginErrorBoundary (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:538:5)
    at Suspense
    at Result (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:635:21)
    at article
    at Content (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:5166:11)
    at RoutedTabs (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:5285:11)
    at main
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:41:24)
    at Page (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:6258:11)
    at EntityLayout (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-a2e41e34.esm.js:1161:5)
    at EntitySwitch (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-a2e41e34.esm.js:1341:110)
    at EntitySwitch (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-a2e41e34.esm.js:1341:110)
    at B (webpack-internal:///../../node_modules/react-router/index.js:35:616)
    at AnalyticsContext (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:72:11)
    at AsyncEntityProvider (webpack-internal:///../../node_modules/@backstage/plugin-catalog-react/dist/esm/useEntity-de64059a.esm.js:33:11)
    at CatalogEntityPage (webpack-internal:///../../node_modules/@backstage/plugin-catalog/dist/esm/index-f0e32dd1.esm.js:40:162)
    at RoutableExtensionWrapper (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:572:31)
    at PluginProvider (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/esm/usePluginOptions-68e31f9f.esm.js:13:11)
    at AnalyticsContext (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:72:11)
    at PluginErrorBoundary (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:538:5)
    at Suspense
    at Result (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:635:21)
    at D (webpack-internal:///../../node_modules/react-router/index.js:35:685)
    at FlatRoutes (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:3364:81)
    at div
    at StyledComponent (webpack-internal:///../../node_modules/@material-ui/styles/esm/styled/styled.js:95:28)
    at SidebarPinStateProvider (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:3769:11)
    at SidebarPage (webpack-internal:///../../node_modules/@backstage/core-components/dist/index.esm.js:4031:82)
    at Root (webpack-internal:///./src/components/Root/Root.tsx:107:17)
    at D (webpack-internal:///../../node_modules/react-router/index.js:35:685)
    at E (webpack-internal:///../../node_modules/react-router/index.js:38:820)
    at x (webpack-internal:///../../node_modules/react-router/index.js:37:23)
    at w (webpack-internal:///../../node_modules/react-router-dom/index.js:42:23)
    at AppRouter (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2164:138)
    at RoutingProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2713:3)
    at ThemeProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/ThemeProvider/ThemeProvider.js:41:24)
    at StylesProvider (webpack-internal:///../../node_modules/@material-ui/styles/esm/StylesProvider/StylesProvider.js:49:24)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:42:5)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:51:5)
    at ThemeProvider (webpack-internal:///../../node_modules/@mui/material/styles/ThemeProvider.js:23:14)
    at StyledEngineProvider (webpack-internal:///../../node_modules/@mui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:28:5)
    at UnifiedThemeProvider (webpack-internal:///../../node_modules/@backstage/theme/dist/index.esm.js:659:11)
    at Provider (webpack-internal:///../../node_modules/@backstage/app-defaults/dist/index.esm.js:337:18)
    at AppThemeProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2904:29)
    at AppContextProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:2784:3)
    at ApiProvider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:80:11)
    at Provider (webpack-internal:///../../node_modules/@backstage/core-app-api/dist/index.esm.js:3167:25)
    at App
<details>

**Comment by dfl-aeb** [comment]
I have managed to debug the error. It occurs when no history details can be retrieved from ArgoCD for an app. 
In our case, this was because an app could not be deployed initially due to a Helm error or ImagePullBackupOffs.
Perhaps one could catch such an error and then simply return "Unkown"?
