### ISSUE TITLE
[Rag-AI] Error 500 when creating embeddings with AuthMiddleWare enabled

### ISSUE THREAD

**Issue by fjudith** [RoadieHQ/roadie-backstage-plugins#1300]
When [calling the endpoint](./plugins/backend/rag-ai-backend#calling-the-endpoint) for embeddings creation, the API returns an 500 HTTP error when the [`authMiddleware` is configured](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md) on the `/catalog` backend router to protect anonymous queries.

## Expected Behavior

Calling the endpoint should work the same way as cases where the `authMiddleware` is not implemented 

## Current Behavior

Below the error message with api request authentication enabled.

```bash
[1] 2024-03-22T22:11:41.763Z backstage info 127.0.0.1 - - [22/Mar/2024:22:11:41 +0000] "GET /api/auth/.well-known/jwks.json HTTP/1.1" 200 754 "-" "-" type=incomingRequest
[1] 2024-03-22T22:11:41.769Z ai info Creating embeddings for source catalog type=plugin
[1] 2024-03-22T22:11:41.771Z backstage info 127.0.0.1 - - [22/Mar/2024:22:11:41 +0000] "GET /api/catalog/entities?filter=kind%3DComponent HTTP/1.1" 401 12 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)" type=incomingRequest
[1] 2024-03-22T22:11:41.773Z backstage error Request failed with status 500 Request failed with 401 Error type=errorHandler response=[object Response] body=[object Object] cause=Error: Request failed with status 401 Unauthorized, Unauthorized name=ResponseError stack=ResponseError: Request failed with 401 Error
[1]     at Function.fromResponse (/home/fjudith/git/alithya/cloud/toolbox/backstage-app/node_modules/@backstage/errors/src/errors/ResponseError.ts:73:12)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at CatalogClient.requestRequired (/home/fjudith/git/alithya/cloud/toolbox/backstage-app/node_modules/@backstage/catalog-client/src/CatalogClient.ts:438:13)
[1]     at CatalogClient.getEntities (/home/fjudith/git/alithya/cloud/toolbox/backstage-app/node_modules/@backstage/catalog-client/src/CatalogClient.ts:130:22)
[1]     at RoadieBedrockAugmenter.deleteEmbeddings (/home/fjudith/git/alithya/cloud/toolbox/backstage-app/plugins/rag-ai-backend-retrieval-augmenter/src/indexing/DefaultVectorAugmentationIndexer.ts:143:23)
[1]     at RoadieBedrockAugmenter.createEmbeddings (/home/fjudith/git/alithya/cloud/toolbox/backstage-app/plugins/rag-ai-backend-retrieval-augmenter/src/indexing/DefaultVectorAugmentationIndexer.ts:133:5)
[1]     at createEmbeddings (/home/fjudith/git/alithya/cloud/toolbox/backstage-app/plugins/rag-ai-backend/src/service/RagAiController.ts:71:32)
[1] 2024-03-22T22:11:41.774Z backstage info 127.0.0.1 - - [22/Mar/2024:22:11:41 +0000] "POST /api/rag-ai/embeddings/catalog HTTP/1.1" 500 - "-" "vscode-restclient" type=incomingRequest
```

## Steps to Reproduce

Follow the [Authenticate API Request (Backstage <=1.23.4)](https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/authenticate-api-requests.md)
Add the Rag-AI plugin configured for either Bedrock or OpenAI.
Send a request for the Catalog embeddings creation (./plugins/backend/rag-ai-backend#calling-the-endpoint)

## Possible Solution

The seems to come from the `DefaultVectorAugmentationIndexer` which does not generate the appropriate token before calling the `/catalog` API endpoint.

## Context

Rag-AI plugin work perfectly fine without the authMiddleware configured in the `packages/backend/src/index.ts`.

```diff
const apiRouter = Router();
  apiRouter.use(cookieParser());
  // The auth route must be publicly available as it is used during login
  apiRouter.use('/auth', await auth(authEnv));
  // Add a simple endpoint to be used when setting a token cookie
  apiRouter.use('/cookie', authMiddleware, (_req, res) => {
    res.status(200).send(`Coming right up`);
  });
- apiRouter.use('/catalog', authMiddleware, await catalog(catalogEnv));
+ apiRouter.use('/catalog', await catalog(catalogEnv));
  apiRouter.use('/scaffolder', authMiddleware, await scaffolder(scaffolderEnv));
  apiRouter.use('/techdocs', authMiddleware, await techdocs(techdocsEnv));
  apiRouter.use('/proxy', await proxy(proxyEnv));
  apiRouter.use('/search', authMiddleware, await search(searchEnv));
  apiRouter.use('/permission', authMiddleware, await permission(permissionEnv));
  apiRouter.use('/rag-ai', authMiddleware, await ai(aiEnv));
  // Add backends ABOVE this line; this 404 handler is the catch-all fallback
  apiRouter.use(authMiddleware, notFoundHandler());

```

## Your Environment

- `@backstage`: 1.23.4
- `@roadiehq/rag-ai`: 0.1.0

**Comment by Xantier** [comment]
Thanks @fjudith , 

Would you be able to create a PR for this so we can get this fixed?

**Comment by fjudith** [comment]
Sure, trying currently to resolve this issue i'll we happy to contribute.

**Comment by Xantier** [comment]
Thanks @fjudith, If you jump into our Discord channel, we've outlined few places where these modifications would possibly needed to be made
