### ISSUE TITLE
RAG AI Backend - Failed to retrieve data from path query/catalog

### ISSUE THREAD

**Issue by brataaaan** [RoadieHQ/roadie-backstage-plugins#1389]
The backend spins up, but when I ask a question in the frontend it response the following after a ~half a minute:
<img width="514" alt="Bildschirmfoto 2024-05-16 um 01 43 33" src="https://github.com/RoadieHQ/roadie-backstage-plugins/assets/61033560/ec3aa357-b9d1-471c-9987-21826a1d9f76">

The backend logs state the following:
```zsh
[1] 2024-05-15T23:40:55.748Z ai info Received 0 results when querying augmentations from search. type=plugin
[1] 2024-05-15T23:40:55.748Z ai info Starting to prompt LLM. type=plugin
[1] 2024-05-15T23:42:46.539Z backstage error Request failed with status 500 [object Object] type=errorHandler attemptNumber=7 retriesLeft=0 stack=Error: [object Object]
[1]     at /project/app/node_modules/@langchain/core/dist/utils/async_caller.cjs:98:23
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1]     at async RetryOperation._fn (/project/app/node_modules/p-retry/index.js:50:12)
```

## Current Behavior

Plugin does not work.

## Context

I am using some custom `augmentationIndexer` for Azure OpenAI Model. (Oriented to the Roadie solution)

## Your Environment

Running Backstage 1.23.2

**Comment by Xantier** [comment]
Thanks, this looks to be missing some debugging information about the error message and the configured setup. I'll close this for now. Feel free to reopen with more actionable info.
