### ISSUE TITLE
Error in configuring JIRA plugin

### ISSUE THREAD

**Issue by cbwilliamsnh** [RoadieHQ/roadie-backstage-plugins#251]
I'm trying to install the JIRA plugin per instructions here:

https://github.com/RoadieHQ/backstage-plugin-jira#:~:text=How%20to%20use%20Jira%20plugin%20in%20Backstage%20Add,components%20Get%20and%20provide%20JIRA_TOKEN%20as%20env%20variable%3A

When I go to access a catalog entity with the jira annotations I get the following:

```
Error
Error

Message
No implementation available for apiRef{plugin.jira.service}

Stack Trace
Error: No implementation available for apiRef{plugin.jira.service}
    at useApi (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:100:11)
    at useProjectInfo (webpack-internal:///../../node_modules/@roadiehq/backstage-plugin-jira/dist/index.esm.js:288:81)
    at JiraCard (webpack-internal:///../../node_modules/@roadiehq/backstage-plugin-jira/dist/index.esm.js:587:7)
    at renderWithHooks (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14804:18)
    at mountIndeterminateComponent (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17483:13)
    at beginWork (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:18597:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:189:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:238:16)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:293:31)
    at beginWork$1 (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23204:7)```

What am I missing/doing wrong?

**Comment by Irma12** [comment]
Hey @cbwilliamsnh, sorry about the issue you are experiencing. There was an update from Backstage last week and some versions of the packages used in plugins are updated, so we need to take a look and update those in our plugins. However, currently whole team is working on other features and this is something we will take a look as soon as possible this week but I am not 100% sure about the timeline. Thank you for sharing this with us, I hope we will resolve the issue soon.

**Comment by cbwilliamsnh** [comment]
@Irma12 not what I wanted to do but including the source of the JIRA plugin in my scaffolded app solved the problem (temporarily). So clearly the plugin has a different react-dom/react version than my scaffolded app.

**Comment by cbwilliamsnh** [comment]
Brand new scaffolded app created with the 2021-09-23 release branch of backstage. @roadiehq/backstage-jira-plugin added per instructions. Still seeing:

```
Error
Error

Message
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

Stack Trace
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at resolveDispatcher (webpack-internal:///../../../node_modules/react/cjs/react.development.js:1465:13)
    at useContext (webpack-internal:///../../../node_modules/react/cjs/react.development.js:1473:20)
    at React$$1.useContext (webpack-internal:///../../../node_modules/react-hot-loader/dist/react-hot-loader.development.js:2979:27)
    at useVersionedContext (webpack-internal:///../../../packages/version-bridge/src/lib/VersionedContext.ts:80:59)
    at useApp (webpack-internal:///../../../packages/core-plugin-api/src/app/useApp.tsx:28:83)
    at Result (webpack-internal:///../../../packages/core-plugin-api/src/extensions/extensions.tsx:140:65)
    at renderWithHooks (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14804:18)
    at mountIndeterminateComponent (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17483:13)
    at beginWork (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:18597:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:189:14)```

**Comment by cbwilliamsnh** [comment]
@Irma12 I went ahead a did that and I my configuration in app-config.yaml now matches the version of backstage that is working but when I run your scaffolded app I get a 404 back from the jira card (I added the annotations to one catalog entity). Looking into seeing if there's something different...

**Comment by zhyu** [comment]
I'm facing the same issue.

I'm on Backstage `1.1.1` and
```
"@backstage/catalog-model": "^1.0.0",
"@backstage/core-components": "^0.9.0",
"@backstage/plugin-catalog-react": "^1.0.0",
```

I first tried the latest version of the jira plugin, which is `2.1.1`. And I got the error:
```
Error
Error

Message
No implementation available for apiRef{plugin.jira.service}

Stack Trace
Error: No implementation available for apiRef{plugin.jira.service}
    at useApi (webpack-internal:///../../node_modules/@backstage/core-plugin-api/dist/index.esm.js:96:11)
    at useProjectInfo (webpack-internal:///../../node_modules/@roadiehq/backstage-plugin-jira/dist/index.esm.js:289:81)
    at JiraCard (webpack-internal:///../../node_modules/@roadiehq/backstage-plugin-jira/dist/index.esm.js:591:7)
    at renderWithHooks (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:14986:18)
    at updateFunctionComponent (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:17357:20)
    at mountLazyComponent (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:17678:17)
    at beginWork (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:19056:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:3946:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:3995:16)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/@hot-loader/react-dom-v17/cjs/react-dom.development.js:4057:31)
```

Then I tried to downgrade the jira plugin to `2.0.2`, which uses the same version of `@backstage/catalog-model`, `@backstage/core-components`, and `@backstage/plugin-catalog-react` as my application. However, the error persists.

Any idea how should I troubleshoot?
