### ISSUE TITLE
[plugin/catalog-backend-module-okta] - throws Not initialized Error

### ISSUE THREAD

**Issue by laughingman-hass** [RoadieHQ/roadie-backstage-plugins#661]
When starting the backstage dev server a `Not initalized` Error is thown

## Expected Behavior

The startup process should initialize with no errors and it should create the user and group entities from Okta

## Current Behavior

The backend startup returns the following error.

```
[1] /Users/dev/backstage/node_modules/@roadiehq/catalog-backend-module-okta/dist/index.cjs.js:76
[1]                     throw new Error("Not initialized");
[1]                           ^
[1]
[1] Error: Not initialized
[1]     at OktaGroupEntityProvider.run (/Users/dev/backstage/node_modules/@roadiehq/catalog-backend-module-okta/dist/index.cjs.js:76:10)
[1]     at createPlugin (webpack-internal:///./src/plugins/catalog.ts:29:17)
[1]     at async main (webpack-internal:///./src/index.ts:90:29)
```

## Steps to Reproduce

From a new backstage app setup, update the following files.

```ts
// packages/backend/src/plugins/catalog.ts

import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import { OktaGroupEntityProvider } from '@roadiehq/catalog-backend-module-okta';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);

  const oktaConfig =
    env.config.getOptionalConfigArray('catalog.providers.okta') || [];
  const groupProvider = OktaGroupEntityProvider.fromConfig(oktaConfig[0], env);

  builder.addEntityProvider(groupProvider);
  builder.addProcessor(new ScaffolderEntitiesProcessor());

  groupProvider.run();

  const { processingEngine, router } = await builder.build();
  await processingEngine.start();
  return router;
}
```

```
# app-config.yaml
...
catalog:
  providers:
    okta:
      - orgUrl: 'https://xxxxxxx.oktapreview.com'
        token:
          $env: OKTA_TOKEN
...
```

Run `yarn dev`

## Context

I'm unsure why the connection to Okta is not being made

## Your Environment

```json
{
    "@backstage/backend-common": "^0.15.0",
    "@backstage/backend-tasks": "^0.3.4",
    "@backstage/catalog-client": "^1.0.4",
    "@backstage/catalog-model": "^1.1.0",
    "@backstage/config": "^1.0.1",
    "@backstage/plugin-app-backend": "^0.3.35",
    "@backstage/plugin-auth-backend": "^0.15.1",
    "@backstage/plugin-catalog-backend": "^1.3.1",
    "@backstage/plugin-permission-common": "^0.6.3",
    "@backstage/plugin-permission-node": "^0.6.4",
    "@backstage/plugin-proxy-backend": "^0.2.29",
    "@backstage/plugin-scaffolder-backend": "^1.5.0",
    "@backstage/plugin-search-backend": "^1.0.1",
    "@backstage/plugin-search-backend-module-pg": "^0.3.6",
    "@backstage/plugin-search-backend-node": "^1.0.1",
    "@backstage/plugin-techdocs-backend": "^1.2.1",
    "@roadiehq/catalog-backend-module-okta": "^0.2.4",
}
```

**Comment by kissmikijr** [comment]
Hey! 
It is not initialized because the init happens in the CatalogBuilder when you build your catalog.
move the groupProvider.run() under the builder.build() and it should have a connection

```diff
// packages/backend/src/plugins/catalog.ts

import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { ScaffolderEntitiesProcessor } from '@backstage/plugin-scaffolder-backend';
import { Router } from 'express';
import { PluginEnvironment } from '../types';
import { OktaGroupEntityProvider } from '@roadiehq/catalog-backend-module-okta';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const builder = await CatalogBuilder.create(env);

  const oktaConfig =
    env.config.getOptionalConfigArray('catalog.providers.okta') || [];
  const groupProvider = OktaGroupEntityProvider.fromConfig(oktaConfig[0], env);

  builder.addEntityProvider(groupProvider);
  builder.addProcessor(new ScaffolderEntitiesProcessor());

- groupProvider.run();

  const { processingEngine, router } = await builder.build();
+ groupProvider.run();
  await processingEngine.start();
  return router;
}
```

**Comment by laughingman-hass** [comment]
Thank you! That was it. 
Can I suggest to update the [README](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/backend/catalog-backend-module-okta) for this plugin as it suggests to do the `groupProvider.run()` before the `builder.build()`.

Closing this issue, since it is resolved on my end.

**Comment by kissmikijr** [comment]
Oh nice, yea I'll update it!
