### ISSUE TITLE
github-insights plugin throws useLocation() error 

### ISSUE THREAD

**Issue by jeremyguarini** [RoadieHQ/roadie-backstage-plugins#696]
When using the roadiehq/backstage-plugin-github-insights and the 1.6.0 codebase of backstage I get an error/stack trace when trying to view the gitlab cicd information for a component.

## Expected Behavior

No error should occur, the gitlab insights plugin should load and show the summary information for the component.

## Current Behavior

I get a stack trace.

## Steps to Reproduce

Using the v1.6.0 code base include the roadie plugin for gitlab insights. Open the portal and navigate to a component. Click on the tab that should load the gitlab insights plugin.

## Possible Solution

Per the stack trace it seems there is a call to useLocation() that should be inside a <Router> context. 

## Context

Not able to view the pretty metrics for a component.

Here is the stack trace I see in the browser

```
Error
Error

Message
useLocation() may be used only in the context of a <Router> component.

Stack Trace
Error: useLocation() may be used only in the context of a <Router> component.
    at l (webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/node_modules/react-router-dom/node_modules/react-router/index.js:30:286)
    at H (webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/node_modules/react-router-dom/node_modules/react-router/index.js:39:299)
    at G (webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/node_modules/react-router-dom/node_modules/react-router/index.js:43:33)
    at E (webpack-internal:///../../node_modules/@loblaw/backstage-plugin-gitlab/node_modules/react-router-dom/node_modules/react-router/index.js:38:870)
    at renderWithHooks (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:17811:13)
    at beginWork (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:19049:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///../../node_modules/react-dom/cjs/react-dom.development.js:4056:31)
```

## Your Environment

- `@backstage/plugin-catalog-react` version:
from package/app/package.json: "@backstage/plugin-catalog-react": "^1.1.4",
- `@backstage/integration` version:
-from package/app/package.jso: "@backstage/integration-react": "^1.1.4",

tested with 
"@roadiehq/backstage-plugin-github-insights": "^2.0.5",
"@roadiehq/backstage-plugin-github-insights": "^2.0.6",
"@roadiehq/backstage-plugin-github-insights": "^2.1.0",

**Comment by jeremyguarini** [comment]
Apologies, I was reporting for the wrong plugin. This can be ignored.
