### ISSUE TITLE
Uncaught (in promise) Error: App context is not available

### ISSUE THREAD

**Issue by LeungYuJP** [RoadieHQ/roadie-backstage-plugins#882]
I import this plugin using react 16.13.1, some error shown below:

```
Uncaught (in promise) Error: App context is not available
    at useApp (index.esm.js:280:1)
    at Result (index.esm.js:551:1)
    at renderWithHooks (react-dom.development.js:14803:1)
    at mountIndeterminateComponent (react-dom.development.js:17482:1)
    at beginWork (react-dom.development.js:18596:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:1)
    at invokeGuardedCallback (react-dom.development.js:292:1)
    at beginWork$1 (react-dom.development.js:23203:1)
    at performUnitOfWork (react-dom.development.js:22154:1)
```
It broke down page rendering, maybe it was caused by function `useApp()` in package `@backstage/version-bridge`.

**Comment by kissmikijr** [comment]
Hi which plugin do you use ?

**Comment by LeungYuJP** [comment]
I used HomePageRSS

> Hi which plugin do you use ?

**Comment by LeungYuJP** [comment]
> Hi which plugin do you use ?

I just try as examples in readme, it shows errors

**Comment by martina-if** [comment]
Hi @LeungYuJP , Can you provide some more information and code excerpts of how you are setting up the plugin? We are using it at the moment in Roadie and we are not having issues so it's difficult to help out.
