### ISSUE TITLE
`OktaOrgEntityProvider` unable to take custom `userNamingStrategy`

### ISSUE THREAD

**Issue by mspiegel31** [RoadieHQ/roadie-backstage-plugins#916]
## Version
`"@roadiehq/catalog-backend-module-okta": "^0.4.8"`

## Expected Behavior
according to [the docs](https://github.com/RoadieHQ/roadie-backstage-plugins/tree/main/plugins/backend/catalog-backend-module-okta#oktaorgentityprovider) for  `OktaOrgEntityProvider`, we should be able to supply a custom naming function for users.

## Current Behavior

when a function is supplied, the `userNamingStrategyFactory` throws an error, rather than accept a function

## Steps to Reproduce
1. use this example config:
 ```ts
import { PluginEnvironment } from '../types';
import { CatalogBuilder } from '@backstage/plugin-catalog-backend';
import { OktaOrgEntityProvider } from '@roadiehq/catalog-backend-module-okta';
import { Router } from 'express';

export default async function createPlugin(
  env: PluginEnvironment,
): Promise<Router> {
  const oktaOrgProvider = OktaOrgEntityProvider.fromConfig(env.config, {
    logger: env.logger,
    groupNamingStrategy: 'kebab-case-name',
    userNamingStrategy: user =>  user.profile.email
  });
  
  const builder = await CatalogBuilder.create(env);
  builder.addEntityProvider(oktaOrgProvider)

  const { processingEngine, router } = await builder.build();

  oktaOrgProvider.run();

  await processingEngine.start();
  return router;
}
```

2. start up a development environment (`yarn dev`)
3. observe the following error

```sh
[1] timestamp: back-of-house info Created UrlReader predicateMux{readers=azure{host=dev.azure.com,authed=false},bitbucketCloud{host=bitbucket.org,authed=true},github{host=github.com,authed=false},gitlab{host=gitlab.com,authed=false},awsS3{host=amazonaws.com,authed=false},fetch{} 
[1] Backend failed to start up Error: Unknown naming strategy (user)=>user.profile.email
[1]     at userNamingStrategyFactory (/Users/someguy/development/production/node_modules/@roadiehq/catalog-backend-module-okta/dist/index.cjs.js:72:13)
[1]     at new OktaOrgEntityProvider (/Users/someguy/development/production/node_modules/@roadiehq/catalog-backend-module-okta/dist/index.cjs.js:230:31)
[1]     at OktaOrgEntityProvider.fromConfig (/Users/someguy/development/production/node_modules/@roadiehq/catalog-backend-module-okta/dist/index.cjs.js:237:12)
[1]     at createPlugin (webpack-internal:///./src/plugins/catalog.ts:42:118)
[1]     at main (webpack-internal:///./src/index.ts:118:97)
```

## Possible Solution
it looks like the `userNamingStrategyFactory` [should handle this case](https://github.com/RoadieHQ/roadie-backstage-plugins/blob/main/plugins/backend/catalog-backend-module-okta/src/providers/userNamingStrategies/userNamingStrategyFactory.ts#L25).  Not sure why it isn't.

Additionally, it would be nice to export the `UserNamingStrategies`/`UserNamingStrategy` type from the package.  I'm currently unable to import it, and receiving this `ts` error: 

```ts
import type { UserNamingStrategies } from '@roadiehq/catalog-backend-module-okta'

Module '"@roadiehq/catalog-backend-module-okta"' declares 'UserNamingStrategies' locally, but it is not exported.ts(2459)
```

## Your Environment

- `@backstage/plugin-catalog-react` version: `N/A`
- `@backstage/integration` version: `"^1.4.3"`

**Comment by punkle** [comment]
Hey thanks for the report. Would you be in a position to provide a pull request?

**Comment by mspiegel31** [comment]
not quickly, unfortunately.  Working under a pretty tight deadline at this point.

**Comment by punkle** [comment]
What version of the okta plugin are you using here?
